// Initial schema: every table as of the first production release.
module.exports = class Initial1790771207300 {
  name = "Initial1790771207300"

  async up(q) {
    await q.query('CREATE EXTENSION IF NOT EXISTS "uuid-ossp"')
    await q.query("CREATE TABLE \"organizations\" (\"id\" uuid NOT NULL DEFAULT uuid_generate_v4(), \"name\" character varying(200) NOT NULL, \"slug\" character varying(80) NOT NULL, \"logo\" text, \"require_separate_approver\" boolean NOT NULL DEFAULT true, \"key_id\" character varying(64) NOT NULL, \"public_key\" text NOT NULL, \"private_key_enc\" text NOT NULL, \"verification_status\" character varying(20) NOT NULL DEFAULT 'unverified', \"legal_name\" character varying(200), \"registration_number\" character varying(100), \"registration_country\" character varying(2), \"domain\" character varying(253), \"domain_token\" character varying(64), \"domain_verified_at\" TIMESTAMP WITH TIME ZONE, \"verification_requested_at\" TIMESTAMP WITH TIME ZONE, \"verified_at\" TIMESTAMP WITH TIME ZONE, \"verified_by\" character varying(200), \"verification_note\" text, \"created_at\" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), \"updated_at\" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT \"UQ_963693341bd612aa01ddf3a4b68\" UNIQUE (\"slug\"), CONSTRAINT \"PK_6b031fcd0863e3f6b44230163f9\" PRIMARY KEY (\"id\"))")
    await q.query("CREATE TABLE \"users\" (\"id\" uuid NOT NULL DEFAULT uuid_generate_v4(), \"organization_id\" uuid NOT NULL, \"email\" character varying(254) NOT NULL, \"name\" character varying(200) NOT NULL, \"qualification\" character varying(500) NOT NULL DEFAULT '', \"signature\" text, \"role\" character varying(20) NOT NULL, \"password_hash\" character varying(100) NOT NULL, \"active\" boolean NOT NULL DEFAULT true, \"must_change_password\" boolean NOT NULL DEFAULT false, \"token_version\" integer NOT NULL DEFAULT '0', \"created_at\" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), \"updated_at\" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT \"UQ_97672ac88f789774dd47f7c8be3\" UNIQUE (\"email\"), CONSTRAINT \"PK_a3ffb1c0c8416b9fc6f907b7433\" PRIMARY KEY (\"id\"))")
    await q.query("CREATE INDEX \"IDX_21a659804ed7bf61eb91688dea\" ON \"users\" (\"organization_id\")")
    await q.query("CREATE TABLE \"templates\" (\"id\" uuid NOT NULL DEFAULT uuid_generate_v4(), \"organization_id\" uuid NOT NULL, \"name\" character varying(200) NOT NULL, \"description\" text NOT NULL DEFAULT '', \"current_version_id\" uuid, \"next_sequence\" integer NOT NULL DEFAULT '1', \"archived\" boolean NOT NULL DEFAULT false, \"created_at\" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), \"updated_at\" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT \"PK_515948649ce0bbbe391de702ae5\" PRIMARY KEY (\"id\"))")
    await q.query("CREATE INDEX \"IDX_e1a4d8ae904ce011b0a81a089a\" ON \"templates\" (\"organization_id\")")
    await q.query("CREATE TABLE \"template_versions\" (\"id\" uuid NOT NULL DEFAULT uuid_generate_v4(), \"template_id\" uuid NOT NULL, \"organization_id\" uuid NOT NULL, \"version\" integer NOT NULL, \"kind\" character varying(10) NOT NULL DEFAULT 'html', \"html\" text NOT NULL DEFAULT '', \"layout\" jsonb, \"source_hash\" character varying(64), \"schema\" jsonb NOT NULL, \"settings\" jsonb NOT NULL DEFAULT '{}', \"content_hash\" character varying(64) NOT NULL, \"created_by\" uuid, \"created_at\" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT \"UQ_e7d4ea0bee357b340b1bf971d37\" UNIQUE (\"template_id\", \"version\"), CONSTRAINT \"PK_cfc439255ca2725f4102c554d41\" PRIMARY KEY (\"id\"))")
    await q.query("CREATE TABLE \"documents\" (\"id\" uuid NOT NULL DEFAULT uuid_generate_v4(), \"organization_id\" uuid NOT NULL, \"template_id\" uuid NOT NULL, \"template_version_id\" uuid NOT NULL, \"document_no\" character varying(120) NOT NULL, \"status\" character varying(20) NOT NULL DEFAULT 'draft', \"data\" jsonb NOT NULL, \"public_id\" character varying(40), \"created_by\" uuid NOT NULL, \"submitted_at\" TIMESTAMP WITH TIME ZONE, \"review_note\" text, \"issued_by\" uuid, \"issued_at\" TIMESTAMP WITH TIME ZONE, \"revoked_by\" uuid, \"revoked_at\" TIMESTAMP WITH TIME ZONE, \"revoke_reason\" text, \"supersedes_id\" uuid, \"superseded_by_id\" uuid, \"signed_payload\" jsonb, \"content_hash\" character varying(64), \"signature\" text, \"key_id\" character varying(64), \"pdf_status\" character varying(20), \"pdf_path\" character varying(500), \"pdf_hash\" character varying(64), \"created_at\" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), \"updated_at\" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT \"UQ_0232c98cbeb857502dc7e5a9365\" UNIQUE (\"public_id\"), CONSTRAINT \"UQ_945e4d136ae6cd24cc958407a23\" UNIQUE (\"organization_id\", \"document_no\"), CONSTRAINT \"PK_ac51aa5181ee2036f5ca482857c\" PRIMARY KEY (\"id\"))")
    await q.query("CREATE INDEX \"IDX_e1c5c9593bc8bb7b6c35a59e7e\" ON \"documents\" (\"organization_id\", \"status\")")
    await q.query("CREATE TABLE \"platform_admins\" (\"id\" uuid NOT NULL DEFAULT uuid_generate_v4(), \"email\" character varying(254) NOT NULL, \"name\" character varying(200) NOT NULL, \"password_hash\" character varying(100) NOT NULL, \"totp_secret_enc\" text, \"totp_enabled\" boolean NOT NULL DEFAULT false, \"totp_last_step\" integer NOT NULL DEFAULT '0', \"must_change_password\" boolean NOT NULL DEFAULT true, \"active\" boolean NOT NULL DEFAULT true, \"token_version\" integer NOT NULL DEFAULT '0', \"last_login_at\" TIMESTAMP WITH TIME ZONE, \"created_at\" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), \"updated_at\" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT \"UQ_7ddfa7abfaf477f671ccc566c83\" UNIQUE (\"email\"), CONSTRAINT \"PK_faecb3398d1962507b44c76e4f0\" PRIMARY KEY (\"id\"))")
    await q.query("CREATE TABLE \"jobs\" (\"id\" BIGSERIAL NOT NULL, \"type\" character varying(60) NOT NULL, \"payload\" jsonb NOT NULL DEFAULT '{}', \"status\" character varying(20) NOT NULL DEFAULT 'queued', \"attempts\" integer NOT NULL DEFAULT '0', \"max_attempts\" integer NOT NULL DEFAULT '5', \"run_at\" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), \"locked_at\" TIMESTAMP WITH TIME ZONE, \"locked_by\" character varying(100), \"last_error\" text, \"created_at\" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), \"updated_at\" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT \"PK_cf0a6c42b72fcc7f7c237def345\" PRIMARY KEY (\"id\"))")
    await q.query("CREATE INDEX \"IDX_41842dd8c741ac472b958f04db\" ON \"jobs\" (\"status\", \"run_at\")")
    await q.query("CREATE TABLE \"audit_events\" (\"id\" BIGSERIAL NOT NULL, \"organization_id\" uuid, \"user_id\" uuid, \"action\" character varying(60) NOT NULL, \"entity_type\" character varying(30), \"entity_id\" character varying(64), \"details\" jsonb NOT NULL DEFAULT '{}', \"ip\" character varying(64), \"created_at\" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT \"PK_910f64d901a5c3e9878f0d4a407\" PRIMARY KEY (\"id\"))")
    await q.query("CREATE INDEX \"IDX_29b7786b58e504f4f044ad8b7e\" ON \"audit_events\" (\"organization_id\", \"created_at\")")
    await q.query("CREATE INDEX \"IDX_24530679b55965efb260852679\" ON \"audit_events\" (\"entity_id\")")
  }

  async down(q) {
    await q.query("DROP INDEX \"public\".\"IDX_24530679b55965efb260852679\"")
    await q.query("DROP INDEX \"public\".\"IDX_29b7786b58e504f4f044ad8b7e\"")
    await q.query("DROP TABLE \"audit_events\"")
    await q.query("DROP INDEX \"public\".\"IDX_41842dd8c741ac472b958f04db\"")
    await q.query("DROP TABLE \"jobs\"")
    await q.query("DROP TABLE \"platform_admins\"")
    await q.query("DROP INDEX \"public\".\"IDX_e1c5c9593bc8bb7b6c35a59e7e\"")
    await q.query("DROP TABLE \"documents\"")
    await q.query("DROP TABLE \"template_versions\"")
    await q.query("DROP INDEX \"public\".\"IDX_e1a4d8ae904ce011b0a81a089a\"")
    await q.query("DROP TABLE \"templates\"")
    await q.query("DROP INDEX \"public\".\"IDX_21a659804ed7bf61eb91688dea\"")
    await q.query("DROP TABLE \"users\"")
    await q.query("DROP TABLE \"organizations\"")
  }
}
